[package]
name = "reqwest_client"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { version = "0.3.31" }
reqwest = { version = "0.12.8", features = ["gzip"] }
tokio = { version = "1.41.0", features = ["fs", "macros", "rt", "rt-multi-thread", "signal", "sync", "time"] }
